package staywell.ui.user.weatherforecast;

public class WeatherPanel extends javax.swing.JPanel
{
    /** Creates new form WeatherPanel */
    public WeatherPanel()
    {
        initComponents();
    }

    public TimeOfDay getTimeOfDay()
    {
        return weatherIcon.getTimeOfDay();
    }

    public void setTimeOfDay(TimeOfDay timeOfDay)
    {
        weatherIcon.setTimeOfDay(timeOfDay);
    }

    public WeatherCondition getCondition()
    {
        return weatherIcon.getCondition();
    }

    public void setCondition(WeatherCondition condition)
    {
        weatherIcon.setCondition(condition);
    }

    public String getTemperature()
    {
        return temperatureLabel.getText();
    }

    public void setTemperature(String temperature)
    {
        temperatureLabel.setText(temperature);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weatherIcon = new WeatherIconPanel();
        temperatureLabel = new TextLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(96, 74));

        weatherIcon.setCondition(WeatherCondition.UNKNOWN);
        weatherIcon.setName("weatherIcon"); // NOI18N

        org.jdesktop.layout.GroupLayout weatherIconLayout = new org.jdesktop.layout.GroupLayout(weatherIcon);
        weatherIcon.setLayout(weatherIconLayout);
        weatherIconLayout.setHorizontalGroup(
            weatherIconLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 96, Short.MAX_VALUE)
        );
        weatherIconLayout.setVerticalGroup(
            weatherIconLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 48, Short.MAX_VALUE)
        );

        temperatureLabel.setFont(new java.awt.Font("Arial", 0, 14));
        temperatureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        temperatureLabel.setName("temperatureLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(weatherIcon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(temperatureLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(weatherIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temperatureLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TextLabel temperatureLabel;
    private WeatherIconPanel weatherIcon;
    // End of variables declaration//GEN-END:variables

}
